name: Unit tests

jobs:
  phpunit:
    name: Run phpunit tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          red: ${{ github.event.inputs.tag }}

      - name: install dependencies
        run: "composer install -noa"
