name: Unit tests

on: [push]

env:
  XDEBUG_MODE: coverage

jobs:
  phpunit-php-7:
    name: Run phpunit tests on php 7.4
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        uses: php-actions/composer@master
        with:
          php_version: 7.4

      - name: Setup PHP with PECL extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: imagick, xdebug

      - name: php version
        run: "php -v"

      - name: run tests
        run: "vendor/bin/phpunit"

  phpunit-php-8:
    name: Run phpunit tests on php 8
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        uses: php-actions/composer@master
        with:
          php_version: 8.0

      - name: php version
        run: "php -v"

      - name: run tests
        run: "vendor/bin/phpunit"
